### ISSUE TITLE
Incorrect handling DPI of the display

### ISSUE THREAD

**Issue by mifopen** [machlibs/imgui#3]
A basic example running on macOS on a screen resolution 2560×1600 (1280×800 logical pixels) looks like the following:
![Screen Cast 2022-11-05 at 11 43 18 AM](https://user-images.githubusercontent.com/19679857/200177962-6eeb5e44-73c2-4603-ac4e-1bd3ab889d49.gif)

It's exactly the same problem as you can see here https://github.com/michal-z/zig-gamedev/commit/d159cf499998a8e56c2564179e7ec88091ad0045

Once I changed
```zig
const window_size = core.getWindowSize();
const fb_size = core.getFramebufferSize();
zgui.io.setDisplayFramebufferScale(
    @intToFloat(f32, window_size.width) / @intToFloat(f32, fb_size.width),
    @intToFloat(f32, window_size.height) / @intToFloat(f32, fb_size.height),
);
```
to this
```zig
zgui.io.setDisplayFramebufferScale(1, 1);
```

and 

```zig
ImGui_ImplMach_CursorPosCallback(pos.x, pos.y);
```
to this
```zig
ImGui_ImplMach_CursorPosCallback(pos.x * 2, pos.y * 2);
```
everything became fixed.

For me getting `core.getWindowSize()` gives 1280×800 and getting `core.getFramebufferSize()` gives 2560×1600, so it was `zgui.io.setDisplayFramebufferScale(0.5, 0.5);` before.
Also, `scale_factor` should be adjusted as well for this case.

**Comment by MusicSoundsBetterWithYou** [comment]
Made pr fixing this issue: https://github.com/machlibs/imgui/pull/4/files#diff-0fcf8b9fea93c1918a84c6db5ae67428d0e40e709aedf08b2997183e61421e9c

**Comment by mifopen** [comment]
Works for me!

**Comment by michal-z** [comment]
Hi Guys, `zgui` author here.

The recommend way of handling DPI is:

"Obtain the desired DPI scale, load your fonts resized with that scale (always round down fonts size to the nearest integer), and scale your Style structure accordingly using `style.ScaleAllSizes()`."

https://github.com/ocornut/imgui/blob/master/docs/FAQ.md#q-how-should-i-handle-dpi-in-my-application

In `zig-gamedev` we always use `zgui.io.setDisplayFramebufferScale(1, 1)` but we scale mouse cursor position, font size and UI size by a `DpiScale`. In that way, cursor callbacks reports coordinates in pixels on all platforms. And also, when `FramebufferScale` is (1,1) we can position our widgets using pixel coordinates on all platforms (this can be important when you use DrawList API).

Furthermore, below code is not a correct way of handling DPI:
```zig
zgui.io.setDisplayFramebufferScale(@intToFloat(f32, fb_size.width) / @intToFloat(f32, window_size.width), @intToFloat(f32, fb_size.height) / @intToFloat(f32, window_size.height));
```
On Windows (with DPI awareness enabled), this code resolves to: `zgui.io.setDisplayFramebufferScale(1, 1)` which means that you will end up with very small font and UI on high-dpi displays. To fix it you need to scale your font and UI with `style.ScaleAllSizes()`.
